# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
          sudo apt-get -y update 
          sudo apt-get -y full-upgrade 
          sudo apt-get -y install build-essential software-properties-common gcc gdb make
    - run: git clone https://github.com/crossdb-org/crossdb.git
    - run: cd crossdb
    - run: make build
    - run: make install 
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test